name: Build angular and deploy to gh pages

on:
  push:
    branches: ['master']

permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: 'pages'
  cancel-in-progress: true
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Install angular cli
        run: npm install @angular/cli

      - name: Build
        run: node_modules/@angular/cli/bin/ng build --base-href 'https://irq0.github.io/alpile/'

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'dist/alpile'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
